# Generated by Django 5.0.6 on 2024-08-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_payment_method_orderhistory_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('aba_bank', 'ABA Bank'), ('acleda_bank', 'ACLEDA Bank'), ('wing_bank', 'Wing Bank')], max_length=50, null=True),
        ),
    ]
