# Generated by Django 5.0.6 on 2024-08-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts'),
        ),
    ]
